/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}", "./!(build|dist|.*)/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "cascadehomestaycom-black-40": "rgba(0, 0, 0, 0.4)",
        "cascadehomestaycom-nero-82": "rgba(255, 255, 255, 0.82)",
        "cascadehomestaycom-sea-green": "#2e8b57",
        "cascadehomestaycom-black-74": "rgba(0, 0, 0, 0.74)",
        "cascadehomestaycom-nero": "#fff",
        "cascadehomestaycom-milano-red": "#a82400",
        "cascadehomestaycom-amaranth": "#ea2c59",
        "cascadehomestaycom-cerulean": "#00aced",
        "cascadehomestaycom-chambray": "#3b5998",
        "cascadehomestaycom-picton-blue": "#2ea3f2",
        "cascadehomestaycom-french-gray": "#c9c8cd",
        "cascadehomestaycom-black": "#000",
        "cascadehomestaycom-linear-black-wild-sand": "rgba(0, 0, 0, 0)",
        "cascadehomestaycom-wild-sand": "#f4f4f4",
        "cascadehomestaycom-picton-blue1": "#3897f0",
        "cascadehomestaycom-feijoa": "#b1d88c",
        "cascadehomestaycom-dove-gray": "#666",
        "cascadehomestaycom-gray": "#808080",
        "cascadehomestaycom-westar": "#e5e3df",
        whitesmoke: "#f5f5f5",
        "cascadehomestaycom-mercury": "#e6e6e6",
        "cascadehomestaycom-royal-blue": "#1a73e8",
        "cascadehomestaycom-scorpion": "#5b5b5b",
        "cascadehomestaycom-nero-02": "rgba(255, 255, 255, 0)",
        "cascadehomestaycom-nero-50": "rgba(255, 255, 255, 0.5)",
      },
      spacing: {},
      fontFamily: {
        "cascadehomestaycom-open-sans-regular-16": "'Open Sans'",
        "cascadehomestaycom-lato-medium-14": "Lato",
        poppins: "Poppins",
        "cascadehomestaycom-arial-narrow-14": "Arial",
        "dancing-script": "'Dancing Script'",
        ledger: "Ledger",
        "cascadehomestaycom-roboto-regular-12": "Roboto",
        "cascadehomestaycom-raleway-bold-14": "Raleway",
      },
      borderRadius: {
        "8xs": "5px",
        "10xs": "3px",
        "3xs": "10px",
        "6xs-3": "6.3px",
        "smi-3": "12.3px",
        "6xs": "7px",
      },
    },
    fontSize: {
      sm: "14px",
      lg: "18px",
      "31xl": "50px",
      base: "16px",
      xl: "20px",
      "3xs": "10px",
      xs: "12px",
      "7xl": "26px",
      mini: "15px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
